from __future__ import annotations

PROJECTS = [
    {
        "id": "langchain",
        "name": "LangChain",
        "full_name": "langchain-ai/langchain",
        "url": "https://github.com/langchain-ai/langchain",
        "description": "大模型应用与 Agent 编排框架，适合拆解工具调用、检索与工作流设计。",
        "job_families": ["ai_app_dev", "algorithm"],
        "topics": ["Agent", "RAG", "Function Calling"],
        "difficulty": "进阶",
        "duration": "2–4 周",
        "value": "简历主项目",
        "copy_angle": "复刻一个最小 Agent，再替换成自己的行业数据与评估集。",
    },
    {
        "id": "llama_index",
        "name": "LlamaIndex",
        "full_name": "run-llama/llama_index",
        "url": "https://github.com/run-llama/llama_index",
        "description": "面向数据增强型大模型应用的框架，包含索引、检索、Agent 与评估能力。",
        "job_families": ["ai_app_dev", "data"],
        "topics": ["RAG", "数据工程", "Evals"],
        "difficulty": "进阶",
        "duration": "2–4 周",
        "value": "简历主项目",
        "copy_angle": "从官方示例复刻检索链路，用个人专业领域的数据做差异化。",
    },
    {
        "id": "autogen",
        "name": "AutoGen",
        "full_name": "microsoft/autogen",
        "url": "https://github.com/microsoft/autogen",
        "description": "微软开源的多智能体框架，适合研究角色协作、工具调用与失败恢复。",
        "job_families": ["ai_app_dev", "algorithm", "ai_product"],
        "topics": ["Agent", "多智能体", "Function Calling"],
        "difficulty": "挑战",
        "duration": "2–4 周",
        "value": "简历主项目",
        "copy_angle": "复刻双 Agent 工作流，再加入任务成功率和失败分类。",
    },
    {
        "id": "crewai",
        "name": "CrewAI",
        "full_name": "crewAIInc/crewAI",
        "url": "https://github.com/crewAIInc/crewAI",
        "description": "以角色和任务为核心的多 Agent 编排框架，容易快速做出可演示工作流。",
        "job_families": ["ai_app_dev", "ai_product"],
        "topics": ["Agent", "自动化", "多智能体"],
        "difficulty": "入门",
        "duration": "1 周",
        "value": "Quick Win",
        "copy_angle": "先复刻一个角色协作案例，再把角色替换为目标行业工作流。",
    },
    {
        "id": "haystack",
        "name": "Haystack",
        "full_name": "deepset-ai/haystack",
        "url": "https://github.com/deepset-ai/haystack",
        "description": "生产级 RAG 与搜索流水线框架，组件边界和工程化设计清晰。",
        "job_families": ["ai_app_dev", "algorithm"],
        "topics": ["RAG", "搜索", "数据工程"],
        "difficulty": "进阶",
        "duration": "2–4 周",
        "value": "简历主项目",
        "copy_angle": "复刻文档问答管线，并增加召回、引用正确率和延迟评估。",
    },
    {
        "id": "openai_evals",
        "name": "OpenAI Evals",
        "full_name": "openai/evals",
        "url": "https://github.com/openai/evals",
        "description": "大模型评估框架与评测样例库，适合建立可复现的质量基线。",
        "job_families": ["algorithm", "ai_app_dev", "data"],
        "topics": ["Evals", "测试", "数据集"],
        "difficulty": "进阶",
        "duration": "1 周",
        "value": "Quick Win",
        "copy_angle": "复刻一个评测任务，替换成自己项目的黄金集和评分规则。",
    },
    {
        "id": "promptfoo",
        "name": "Promptfoo",
        "full_name": "promptfoo/promptfoo",
        "url": "https://github.com/promptfoo/promptfoo",
        "description": "提示词、模型与 RAG 的测试工具，可快速做多模型对比和回归测试。",
        "job_families": ["ai_app_dev", "ai_product", "algorithm"],
        "topics": ["Evals", "Prompt", "模型横评"],
        "difficulty": "入门",
        "duration": "1–3 天",
        "value": "Quick Win",
        "copy_angle": "直接复刻配置，用同一批样本对比两个兼容模型。",
    },
    {
        "id": "phoenix",
        "name": "Phoenix",
        "full_name": "Arize-ai/phoenix",
        "url": "https://github.com/Arize-ai/phoenix",
        "description": "面向 LLM 应用的可观测与评估平台，覆盖 tracing、实验和错误分析。",
        "job_families": ["ai_app_dev", "algorithm", "data"],
        "topics": ["Evals", "可观测", "RAG"],
        "difficulty": "进阶",
        "duration": "1 周",
        "value": "简历主项目",
        "copy_angle": "接入已有 Demo，展示一次真实错误的定位和修复闭环。",
    },
    {
        "id": "fastapi",
        "name": "FastAPI",
        "full_name": "fastapi/fastapi",
        "url": "https://github.com/fastapi/fastapi",
        "description": "现代 Python API 框架，适合补齐接口设计、异步调用和服务化证据。",
        "job_families": ["ai_app_dev", "data"],
        "topics": ["FastAPI", "工程化", "API"],
        "difficulty": "入门",
        "duration": "1–3 天",
        "value": "Quick Win",
        "copy_angle": "复刻官方教程，把一个 notebook 包装为可校验的 API 服务。",
    },
    {
        "id": "pgvector",
        "name": "pgvector",
        "full_name": "pgvector/pgvector",
        "url": "https://github.com/pgvector/pgvector",
        "description": "PostgreSQL 向量检索扩展，适合展示向量存储、过滤和召回权衡。",
        "job_families": ["ai_app_dev", "data"],
        "topics": ["向量数据库", "RAG", "PostgreSQL"],
        "difficulty": "进阶",
        "duration": "1 周",
        "value": "简历主项目",
        "copy_angle": "复刻向量检索，再对比不同索引或过滤条件的召回与延迟。",
    },
    {
        "id": "bentoml",
        "name": "BentoML",
        "full_name": "bentoml/BentoML",
        "url": "https://github.com/bentoml/BentoML",
        "description": "AI 模型与推理服务部署框架，适合补齐打包、服务化和部署证据。",
        "job_families": ["ai_app_dev", "algorithm"],
        "topics": ["部署", "工程化", "推理服务"],
        "difficulty": "进阶",
        "duration": "1 周",
        "value": "简历主项目",
        "copy_angle": "把已有模型或应用封装成服务，记录吞吐和冷启动数据。",
    },
    {
        "id": "mlflow",
        "name": "MLflow",
        "full_name": "mlflow/mlflow",
        "url": "https://github.com/mlflow/mlflow",
        "description": "机器学习实验、模型与部署生命周期平台，适合补齐实验追踪能力。",
        "job_families": ["algorithm", "data"],
        "topics": ["MLOps", "Evals", "实验追踪"],
        "difficulty": "进阶",
        "duration": "1 周",
        "value": "简历主项目",
        "copy_angle": "复刻一次实验追踪，把参数、指标和模型版本形成可回看记录。",
    },
    {
        "id": "dify",
        "name": "Dify",
        "full_name": "langgenius/dify",
        "url": "https://github.com/langgenius/dify",
        "description": "完整的 LLM 应用开发平台，适合拆解产品工作流、知识库和运营能力。",
        "job_families": ["ai_product", "ai_app_dev"],
        "topics": ["RAG", "工作流", "AI 产品"],
        "difficulty": "入门",
        "duration": "1 周",
        "value": "Quick Win",
        "copy_angle": "复刻一个工作流，再从产品指标和失败体验角度做二次设计。",
    },
    {
        "id": "flowise",
        "name": "Flowise",
        "full_name": "FlowiseAI/Flowise",
        "url": "https://github.com/FlowiseAI/Flowise",
        "description": "可视化构建 Agent 与 LLM 工作流的开源工具，适合快速理解编排节点。",
        "job_families": ["ai_product", "ai_app_dev"],
        "topics": ["工作流", "Agent", "低代码"],
        "difficulty": "入门",
        "duration": "1–3 天",
        "value": "Quick Win",
        "copy_angle": "先照着模板跑通，再解释每个节点的输入输出与失败方式。",
    },
    {
        "id": "vllm",
        "name": "vLLM",
        "full_name": "vllm-project/vllm",
        "url": "https://github.com/vllm-project/vllm",
        "description": "高吞吐大模型推理与服务引擎，适合偏算法和基础设施方向的候选人。",
        "job_families": ["algorithm", "ai_app_dev"],
        "topics": ["推理服务", "部署", "性能"],
        "difficulty": "挑战",
        "duration": "长期项目",
        "value": "简历主项目",
        "copy_angle": "复刻本地服务并比较批处理、并发和显存占用。",
    },
    {
        "id": "transformers",
        "name": "Transformers",
        "full_name": "huggingface/transformers",
        "url": "https://github.com/huggingface/transformers",
        "description": "主流预训练模型工具库，适合算法、微调和模型应用基础能力建设。",
        "job_families": ["algorithm", "data"],
        "topics": ["微调", "模型", "数据集"],
        "difficulty": "挑战",
        "duration": "长期项目",
        "value": "简历主项目",
        "copy_angle": "从官方任务示例开始，加入自建数据、基线和误差分析。",
    },
    {
        "id": "ai_town",
        "name": "AI Town",
        "full_name": "a16z-infra/ai-town",
        "url": "https://github.com/a16z-infra/ai-town",
        "description": "可部署的 AI 小镇，多个角色会聊天、记忆和行动，适合做强互动演示。",
        "job_families": ["ai_app_dev", "ai_product"],
        "topics": ["Agent", "角色记忆", "实时互动"],
        "difficulty": "进阶",
        "duration": "2–4 周",
        "value": "简历主项目",
        "copy_angle": "先保留 3 个角色和 1 个场景，再加入可观察的记忆规则与行为评估。",
    },
    {
        "id": "roomgpt",
        "name": "RoomGPT",
        "full_name": "Nutlope/roomGPT",
        "url": "https://github.com/Nutlope/roomGPT",
        "description": "上传房间照片生成不同装修风格，视觉反馈直接，适合快速做出可分享版本。",
        "job_families": ["ai_app_dev", "ai_product"],
        "topics": ["多模态", "图像生成", "网页互动"],
        "difficulty": "入门",
        "duration": "1–3 天",
        "value": "Quick Win",
        "copy_angle": "先复刻上传与生成，再加入风格对比、失败提示和结果收藏。",
    },
    {
        "id": "restore_photos",
        "name": "Restore Photos",
        "full_name": "Nutlope/restorePhotos",
        "url": "https://github.com/Nutlope/restorePhotos",
        "description": "老照片修复应用，任务边界清晰，适合练习 AI API、文件上传和前后对比体验。",
        "job_families": ["ai_app_dev", "ai_product"],
        "topics": ["多模态", "图像修复", "网页互动"],
        "difficulty": "入门",
        "duration": "1–3 天",
        "value": "Quick Win",
        "copy_angle": "复刻最小修复链路，增加样例图库、错误恢复和处理耗时说明。",
    },
    {
        "id": "comfyui",
        "name": "ComfyUI",
        "full_name": "comfyanonymous/ComfyUI",
        "url": "https://github.com/comfyanonymous/ComfyUI",
        "description": "节点式生成式 AI 工作流界面，适合探索图像生成、节点编排和可复用流程。",
        "job_families": ["ai_app_dev", "ai_product", "algorithm"],
        "topics": ["多模态", "图像生成", "工作流"],
        "difficulty": "挑战",
        "duration": "长期项目",
        "value": "简历主项目",
        "copy_angle": "不要复刻完整平台，只挑 4 类核心节点做一个垂直场景工作流。",
    },
    {
        "id": "chatdev",
        "name": "ChatDev",
        "full_name": "OpenBMB/ChatDev",
        "url": "https://github.com/OpenBMB/ChatDev",
        "description": "用多个智能体模拟软件公司协作流程，角色分工鲜明，演示效果强。",
        "job_families": ["ai_app_dev", "ai_product"],
        "topics": ["Agent", "多智能体", "自动化"],
        "difficulty": "进阶",
        "duration": "1 周",
        "value": "简历主项目",
        "copy_angle": "缩减到产品、开发、测试 3 个角色，用任务成功率验证协作是否真的有效。",
    },
    {
        "id": "generative_agents",
        "name": "Generative Agents",
        "full_name": "joonspk-research/generative_agents",
        "url": "https://github.com/joonspk-research/generative_agents",
        "description": "生成式智能体研究项目，角色能形成记忆、反思和计划，适合深入理解 Agent 行为。",
        "job_families": ["algorithm", "ai_app_dev"],
        "topics": ["Agent", "角色记忆", "研究复现"],
        "difficulty": "挑战",
        "duration": "长期项目",
        "value": "简历主项目",
        "copy_angle": "只复现记忆检索与反思机制，用小规模角色实验记录行为差异。",
    },
]

PROJECTS.extend([
    {
        "id": "openai_skills", "name": "OpenAI Skills", "full_name": "openai/skills",
        "url": "https://github.com/openai/skills",
        "description": "OpenAI 官方 Skills 目录，适合学习如何把稳定工作流封装成 Codex 可复用能力。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["Skill", "Codex", "工作流"],
        "difficulty": "入门", "duration": "1–3 天", "value": "Quick Win",
        "copy_angle": "选择一个与你目标岗位相关的 Skill，复刻触发规则、输入输出和验收方式。",
    },
    {
        "id": "anthropic_skills", "name": "Anthropic Skills", "full_name": "anthropics/skills",
        "url": "https://github.com/anthropics/skills",
        "description": "Anthropic 官方技能仓库，覆盖文档、表格、演示稿等真实知识工作场景。",
        "job_families": ["ai_product", "ai_app_dev", "data"], "topics": ["Skill", "文档", "办公自动化"],
        "difficulty": "入门", "duration": "1–3 天", "value": "Quick Win",
        "copy_angle": "复刻一个文档类 Skill，再加入中文材料、错误样本和可验证交付物。",
    },
    {
        "id": "agent_skills", "name": "Agent Skills", "full_name": "addyosmani/agent-skills",
        "url": "https://github.com/addyosmani/agent-skills",
        "description": "生产级 Agent 工程技能集合，覆盖计划、实现、测试、审查和发布流程。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["Skill", "工程化", "测试"],
        "difficulty": "进阶", "duration": "1 周", "value": "简历主项目",
        "copy_angle": "挑一条完整工程链路做复现，记录 Skill 触发前后返工次数和验收结果。",
    },
    {
        "id": "browser_use", "name": "Browser Use", "full_name": "browser-use/browser-use",
        "url": "https://github.com/browser-use/browser-use",
        "description": "让 Agent 理解并操作真实网页的开源框架，适合构建浏览器任务自动化。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["Agent", "浏览器", "自动化"],
        "difficulty": "进阶", "duration": "2–4 周", "value": "简历主项目",
        "copy_angle": "复刻一个网页任务，再加入关键动作确认、失败恢复和任务成功率评估。",
    },
    {
        "id": "gpt_researcher", "name": "GPT Researcher", "full_name": "assafelovic/gpt-researcher",
        "url": "https://github.com/assafelovic/gpt-researcher",
        "description": "自动检索、阅读并生成带来源报告的研究 Agent，适合资料与知识工作场景。",
        "job_families": ["ai_app_dev", "ai_product", "data"], "topics": ["Agent", "搜索", "引用"],
        "difficulty": "进阶", "duration": "2–4 周", "value": "简历主项目",
        "copy_angle": "限定一个垂直主题，增加来源可信度、引用正确率和研究覆盖度评估。",
    },
    {
        "id": "metagpt", "name": "MetaGPT", "full_name": "FoundationAgents/MetaGPT",
        "url": "https://github.com/FoundationAgents/MetaGPT",
        "description": "以软件公司角色分工为核心的多 Agent 框架，适合研究协作与交付质量。",
        "job_families": ["ai_app_dev", "algorithm", "ai_product"], "topics": ["Agent", "多智能体", "软件工程"],
        "difficulty": "挑战", "duration": "长期项目", "value": "简历主项目",
        "copy_angle": "保留需求、开发、测试三个角色，用交付正确率而不是角色数量证明效果。",
    },
    {
        "id": "n8n", "name": "n8n", "full_name": "n8n-io/n8n",
        "url": "https://github.com/n8n-io/n8n",
        "description": "开源工作流自动化平台，可连接模型、表格、邮件、数据库和业务系统。",
        "job_families": ["ai_product", "ai_app_dev", "data"], "topics": ["工作流", "自动化", "集成"],
        "difficulty": "入门", "duration": "1 周", "value": "Quick Win",
        "copy_angle": "复刻一个业务自动化模板，再补充异常分支、人工确认和运行成本记录。",
    },
    {
        "id": "markitdown", "name": "MarkItDown", "full_name": "microsoft/markitdown",
        "url": "https://github.com/microsoft/markitdown",
        "description": "微软开源的文档转 Markdown 工具，适合构建资料预处理和知识库入口。",
        "job_families": ["ai_app_dev", "data", "ai_product"], "topics": ["文档", "数据处理", "RAG"],
        "difficulty": "入门", "duration": "1–3 天", "value": "Quick Win",
        "copy_angle": "复刻多格式转换，为中文 PDF、表格和失败文件增加质量检查报告。",
    },
    {
        "id": "stirling_pdf", "name": "Stirling PDF", "full_name": "Stirling-Tools/Stirling-PDF",
        "url": "https://github.com/Stirling-Tools/Stirling-PDF",
        "description": "功能完整的本地 PDF 工具箱，适合拆解文档处理、隐私和批量任务体验。",
        "job_families": ["ai_product", "ai_app_dev", "data"], "topics": ["PDF", "文档", "本地优先"],
        "difficulty": "进阶", "duration": "1 周", "value": "简历主项目",
        "copy_angle": "选取合并、OCR、脱敏三个流程，做一个面向求职材料的垂直工具。",
    },
    {
        "id": "remotion", "name": "Remotion", "full_name": "remotion-dev/remotion",
        "url": "https://github.com/remotion-dev/remotion",
        "description": "使用 React 编程生成视频的开源框架，适合内容自动化和数据驱动视频。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["视频", "React", "自动生成"],
        "difficulty": "进阶", "duration": "1 周", "value": "简历主项目",
        "copy_angle": "复刻一个模板，把结构化数据和模型输出转换为可批量渲染的短视频。",
    },
    {
        "id": "money_printer_turbo", "name": "MoneyPrinterTurbo", "full_name": "harry0703/MoneyPrinterTurbo",
        "url": "https://github.com/harry0703/MoneyPrinterTurbo",
        "description": "从文案、素材、配音到字幕自动生成短视频，适合拆解内容生产流水线。",
        "job_families": ["ai_product", "ai_app_dev"], "topics": ["视频", "内容生成", "自动化"],
        "difficulty": "进阶", "duration": "2–4 周", "value": "简历主项目",
        "copy_angle": "限定一种内容类型，记录素材命中率、人工修改点和单条视频生成成本。",
    },
    {
        "id": "open_montage", "name": "OpenMontage", "full_name": "calesthio/OpenMontage",
        "url": "https://github.com/calesthio/OpenMontage",
        "description": "开源 AI 视频创作与剪辑项目，适合探索镜头编排、素材选择和成片生成。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["视频", "剪辑", "多模态"],
        "difficulty": "挑战", "duration": "长期项目", "value": "简历主项目",
        "copy_angle": "只复刻脚本到镜头清单的核心链路，增加素材匹配和成片一致性评估。",
    },
    {
        "id": "stable_diffusion_webui", "name": "Stable Diffusion WebUI", "full_name": "AUTOMATIC1111/stable-diffusion-webui",
        "url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        "description": "成熟的 Stable Diffusion 图像生成界面，插件与参数生态丰富。",
        "job_families": ["ai_app_dev", "ai_product", "algorithm"], "topics": ["图像生成", "多模态", "插件"],
        "difficulty": "进阶", "duration": "2–4 周", "value": "简历主项目",
        "copy_angle": "围绕一个垂直视觉场景精简参数，加入提示词版本和结果偏好评估。",
    },
    {
        "id": "invoke_ai", "name": "InvokeAI", "full_name": "invoke-ai/InvokeAI",
        "url": "https://github.com/invoke-ai/InvokeAI",
        "description": "面向创作者的生成式图像平台，包含画布、工作流和资产管理。",
        "job_families": ["ai_product", "ai_app_dev"], "topics": ["图像生成", "画布", "工作流"],
        "difficulty": "挑战", "duration": "长期项目", "value": "简历主项目",
        "copy_angle": "复刻局部重绘或画布流程，用创作者任务完成时间评估交互改造。",
    },
    {
        "id": "phaser", "name": "Phaser", "full_name": "phaserjs/phaser",
        "url": "https://github.com/phaserjs/phaser",
        "description": "成熟的 HTML5 游戏框架，适合快速制作可玩的浏览器互动原型。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["游戏", "网页互动", "Canvas"],
        "difficulty": "入门", "duration": "1–3 天", "value": "Quick Win",
        "copy_angle": "先复刻一个核心循环，再加入由模型生成关卡、角色对白或难度曲线。",
    },
    {
        "id": "pixijs", "name": "PixiJS", "full_name": "pixijs/pixijs",
        "url": "https://github.com/pixijs/pixijs",
        "description": "高性能 2D WebGL 渲染引擎，适合游戏、数据故事和视觉互动。",
        "job_families": ["ai_app_dev", "ai_product"], "topics": ["游戏", "WebGL", "视觉互动"],
        "difficulty": "进阶", "duration": "1 周", "value": "简历主项目",
        "copy_angle": "复刻一个互动场景，再用实时数据或 Agent 状态驱动画面变化。",
    },
    {
        "id": "sandspiel", "name": "Sandspiel", "full_name": "maxbittker/sandspiel",
        "url": "https://github.com/maxbittker/sandspiel",
        "description": "像素材料相互反应的开源沙盒游戏，规则简单但涌现效果强。",
        "job_families": ["ai_app_dev", "algorithm", "ai_product"], "topics": ["游戏", "物理模拟", "像素"],
        "difficulty": "进阶", "duration": "1 周", "value": "简历主项目",
        "copy_angle": "复刻 6 种材料和基础规则，再让模型生成新材料并自动验证规则冲突。",
    },
    {
        "id": "handtrack_js", "name": "Handtrack.js", "full_name": "victordibia/handtrack.js",
        "url": "https://github.com/victordibia/handtrack.js",
        "description": "浏览器端手部检测库，适合制作手势游戏、乐器和无接触交互。",
        "job_families": ["ai_app_dev", "ai_product", "algorithm"], "topics": ["游戏", "计算机视觉", "手势"],
        "difficulty": "入门", "duration": "1–3 天", "value": "Quick Win",
        "copy_angle": "先做三种手势控制，再记录识别延迟、误触和不同光照下的失败样本。",
    },
])

PROJECT_TYPE_BY_ID = {
    "langchain": "Agent 应用", "llama_index": "Agent 应用", "autogen": "Agent 应用",
    "crewai": "Agent 应用", "haystack": "AI 工具", "openai_evals": "数据评测",
    "promptfoo": "数据评测", "phoenix": "数据评测", "fastapi": "AI 工具",
    "pgvector": "AI 工具", "bentoml": "AI 工具", "mlflow": "数据评测",
    "dify": "AI 工具", "flowise": "Agent 应用", "vllm": "AI 工具",
    "transformers": "AI 工具", "ai_town": "游戏互动", "roomgpt": "视觉创作",
    "restore_photos": "视觉创作", "comfyui": "视觉创作", "chatdev": "Agent 应用",
    "generative_agents": "Agent 应用", "openai_skills": "Skill / 插件",
    "anthropic_skills": "Skill / 插件", "agent_skills": "Skill / 插件",
    "browser_use": "Agent 应用", "gpt_researcher": "Agent 应用", "metagpt": "Agent 应用",
    "n8n": "AI 工具", "markitdown": "AI 工具", "stirling_pdf": "AI 工具",
    "remotion": "视觉创作", "money_printer_turbo": "视觉创作", "open_montage": "视觉创作",
    "stable_diffusion_webui": "视觉创作", "invoke_ai": "视觉创作",
    "phaser": "游戏互动", "pixijs": "游戏互动", "sandspiel": "游戏互动",
    "handtrack_js": "游戏互动",
}

BUSINESS_DOMAINS_BY_ID = {
    "langchain": ["开发者工具", "办公效率"], "llama_index": ["文档知识", "开发者工具"],
    "autogen": ["开发者工具", "办公效率"], "crewai": ["办公效率", "开发者工具"],
    "haystack": ["文档知识", "开发者工具"], "openai_evals": ["开发者工具"],
    "promptfoo": ["开发者工具"], "phoenix": ["开发者工具"], "fastapi": ["开发者工具"],
    "pgvector": ["文档知识", "开发者工具"], "bentoml": ["开发者工具"],
    "mlflow": ["开发者工具", "教育学习"], "dify": ["办公效率", "文档知识"],
    "flowise": ["办公效率", "文档知识"], "vllm": ["开发者工具"],
    "transformers": ["教育学习", "开发者工具"], "ai_town": ["游戏娱乐"],
    "roomgpt": ["图片设计", "电商营销"], "restore_photos": ["图片设计"],
    "comfyui": ["图片设计", "电商营销"], "chatdev": ["开发者工具"],
    "generative_agents": ["游戏娱乐", "教育学习"], "openai_skills": ["开发者工具", "办公效率"],
    "anthropic_skills": ["文档知识", "办公效率"], "agent_skills": ["开发者工具"],
    "browser_use": ["办公效率", "开发者工具"], "gpt_researcher": ["文档知识", "办公效率"],
    "metagpt": ["开发者工具"], "n8n": ["办公效率", "电商营销"],
    "markitdown": ["文档知识"], "stirling_pdf": ["文档知识", "办公效率"],
    "remotion": ["视频", "电商营销"], "money_printer_turbo": ["视频", "电商营销"],
    "open_montage": ["视频"], "stable_diffusion_webui": ["图片设计"],
    "invoke_ai": ["图片设计"], "phaser": ["游戏娱乐", "教育学习"],
    "pixijs": ["游戏娱乐", "图片设计"], "sandspiel": ["游戏娱乐", "教育学习"],
    "handtrack_js": ["游戏娱乐", "教育学习"],
}

for project in PROJECTS:
    project["project_type"] = PROJECT_TYPE_BY_ID.get(project["id"], "AI 工具")
    project["business_domains"] = BUSINESS_DOMAINS_BY_ID.get(project["id"], ["开发者工具"])
    project["category"] = "fun" if project["project_type"] in {"视觉创作", "游戏互动"} else "useful"
    project["source"] = "GitHub"
    project["github_verified"] = True


DAILY_BRIEFS = [
    {
        "title": "模型能力之外，评估链路正在成为 AI 应用工程的标准配置",
        "fact": "越来越多开源框架把评估、追踪和数据集管理放进应用开发主流程。",
        "why": "面试中只讲“接了模型 API”已经不够，能解释如何发现和修复失败更有区分度。",
        "tags": ["Evals", "工程化"],
    },
    {
        "title": "Agent 项目的竞争点从角色数量转向任务成功率",
        "fact": "多 Agent 框架继续增长，但生产实践更关注工具可靠性、状态恢复和成本。",
        "why": "做项目时应减少角色堆叠，增加失败分类、重试策略和可观测记录。",
        "tags": ["Agent", "面试谈资"],
    },
    {
        "title": "OpenAI-compatible 接口正在降低多模型横评成本",
        "fact": "多家模型服务提供相近的 chat completions 接口，业务层可以通过适配器切换。",
        "why": "同一任务跑多模型并记录质量、延迟和成本，是非常适合作品集展示的工程能力。",
        "tags": ["模型横评", "架构"],
    },
    {
        "title": "RAG 的面试重点逐渐回到数据与评估",
        "fact": "切分、召回、引用和错误分析比单纯展示聊天界面更能说明项目深度。",
        "why": "准备项目时至少保留一组黄金问题和失败案例，避免停留在 Demo 层。",
        "tags": ["RAG", "数据"],
    },
    {
        "title": "本地优先与隐私设计成为简历类 AI 产品的信任基础",
        "fact": "简历包含个人敏感信息，日志、训练用途和删除入口需要在产品层明确。",
        "why": "能说明数据边界和删除机制，会让项目从功能 Demo 更接近真实产品。",
        "tags": ["隐私", "产品"],
    },
]
